import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "../public/styles/global.css";
import Head from "next/head"; // Import Next.js <Head> component

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Becky Schlomann",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html>
      <body>
        <LayoutContent>{children}</LayoutContent>
        {/* <CookieConsent
          location="bottom"
          buttonText="Accept"
          declineButtonText="Decline"
          enableDeclineButton
          onAccept={() => console.log("Cookies accepted")}
          onDecline={() => console.log("Cookies declined")}
          style={{ background: "#c363d0", color: "#fff" }}
          buttonStyle={{ background: "#3b688c", color: "#fff", fontSize: "14px" }}
          declineButtonStyle={{ background: "#893553", color: "#fff", fontSize: "14px" }}
        >
          This site uses cookies.
        </CookieConsent> */}
      </body>
      </html>
    );
  }

  function LayoutContent({ children }: { children: React.ReactNode }) {
    return (
      <div id="flex-wrapper">
        {/* <Header /> */}
        {children}
        {/* <Footer /> */}
      </div>
    );
  }

